[package]
name = "build-machine-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
sha2.workspace = true
walkdir.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
zip.workspace = true
